version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: yt-subtitles-cli-dev
    volumes:
      - .:/workspace
      - /workspace/.venv  # Don't sync venv folder
    working_dir: /workspace
    command: /bin/bash
    stdin_open: true
    tty: true
